html5rocks/www.html5rocks.com

- content/tutorials/developertools/async-call-stack/fr/index.html
> Full FR L10n for the Async Call Stacks article

- content/tutorials/service-worker/introduction/ko/index.html
Maybe this will be my last work in this year, and I want to say Happy New Year to all of you! :)
> Translated 'introduction to ServiceWorker' into Korean.

- content/tutorials/security/content-security-policy/en/index.html
Old link 404s, new link added.
> Updated link to the Twitter case study on CSP

- content/tutorials/webcomponents/customelements/ja/index.html
Fixed argument of document.registerElement (Add "extends").
> Update /ja/index.html article code sample.

- content/tutorials/offline/quota-research/en/index.html
- content/tutorials/offline/quota-research/ja/index.html
- content/tutorials/offline/quota-research/ko/index.html
Added the result of a survey about Safari 8.
cc: @agektmr
> Update "Working with quota on mobile browsers"

- content/tutorials/offline/quota-research/ko/index.html
> translate the rest into KO

- content/tutorials/speed/html5/en/index.html
The article is a bit out of date. Not sure what html5rocks' retirement policy is.
> Remove no longer accurate/relevant information.

- content/tutorials/security/content-security-policy/en/index.html
- content/tutorials/security/content-security-policy/en/index.markdown
Collaboration with original post author.
> Update to Content Security Policy Post.

- content/tutorials/casestudies/jamwithchrome-audio/en/index.html
- database/profiles.yaml
- database/tutorials.yaml
I fixed the demo for the Jam With Chrome case study and updated my profile while I was at it.
> Fixed broken Jam With Chrome demo 

- content/tutorials/internals/antialiasing-101/zh/index.html
Chinese translation of antialiasing-101
> Chinese translation of antialiasing-101

- content/tutorials/webrtc/basics/en/index.html
As per @juberti comment in #1394.
> Corrected 'FaceTime messenger' to 'Facebook Messenger'

- content/tutorials/file/xhr2/ja/index.html
BlobBuilder was obsoleted.
So, this commit fixed to use Blob.
> Fixed /ja/index.html article code samples

- content/tutorials/speed/layers/en/index.html
- content/tutorials/speed/layers/ko/index.html
- content/tutorials/speed/layers/static/animatedinvalidation.html
- content/tutorials/speed/layers/zh/index.html
addressing ebidel's comment on https://github.com/html5rocks/www.html5rocks.com/pull/1404
> remove empty onclick from layers article

- content/tutorials/webcomponents/imports/en/index.html
- content/tutorials/webcomponents/imports/en/index.md
> Fixes for imports article

- content/tutorials/es7/observe/en/index.html
> Deprecate O.o

- CALENDAR.md
- app.yaml
Might have broken other things.
> Fixing images.

- content/tutorials/offline/storage/en/index.html
> fixing: link to demo broken

- content/tutorials/getusermedia/intro/en/index.html
As per comment from dandv@ on email thread re /web.
> Fixed minor typo

- app.yaml
- content/tutorials/webcomponents/customelements/en/index.html
- content/tutorials/webcomponents/shadowdom-201/en/index.html
- content/tutorials/webcomponents/shadowdom-201/en/index.md
- content/tutorials/webcomponents/shadowdom-301/en/index.html
- content/tutorials/webcomponents/shadowdom-301/en/index.md
- content/tutorials/webcomponents/shadowdom/en/index.html
> Add notes to top of web component articles pointing to d.g.c

- content/tutorials/speed/quick/ko/index.html
The article is "Best Practices for a Faster Web App with HTML5" translated in Korean.
> Translated Best Practices for a Faster Web App with HTML5 in Korean

- content/tutorials/speed/quick/ko/index.html
@cwdoh - dear Changwook, if you don't mind, please take a look at this post and I would love to get your feedback.
@PaulKinlan - Thanks in advance!
> Proofread the typo and misspelling

- content/tutorials/track/basics/ko/index.html
Hello,
This is Jung-Hyun from South Korea. I really enjoy reading tutorials in html5rocks. I translated a tutorial titled "Getting Started With the Track Element" into Korean. I think this is a great tutorial to get a concept of the track element. There are not many Korean resources to learn the track element, so I translated this tutorial into Korean. I hope this will help Koreans understand the track element.
> Translate the track tutorial into Korean

- content/tutorials/webrtc/infrastructure/en/index.html
- content/tutorials/webrtc/infrastructure/ko/index.html
the former was removed but the usage counters remain high.
@samdutton lets hope that "people copy this blindly" works in our favor :-)
> webrtc: update RTCIceServer.url to RTCIceServer.urls

- content/tutorials/getusermedia/intro/en/index.html
- content/tutorials/webrtc/basics/en/index.html
- content/tutorials/webrtc/infrastructure/en/index.html
Also fixed the gUM demos.
Except in a couple of places, I haven't updated otherwise. The articles could all do with a proper review from the WebRTC folks, since they still get a lot of views and we probably want to port to /web.
The translations will also need to be updated.
@cwilso @ebidel @fippo @jpmedley fyi
> Updated WebRTC demos to use mediaDevices.getUserMedia and video.srcObject

- content/tutorials/internals/howbrowserswork/en/index.html
Great read! I fixed some typos along the way.
> Fix typos in "How Browsers Work"

- content/tutorials/es6/promises/en/index.html
Thanks for the great intro on Promises. I needed a refresher!
> Promises tutorial: improve readability

- app.yaml
- content/mobile/index.html
Also makes Web App Field Guide always serve secure
> Remove PSI test from mobile landing page

- content/tutorials/webcomponents/imports/en/index.md
* https://www.html5rocks.com/en/tutorials/webcomponents/imports/
* https://www.chromestatus.com/feature/5144752345317376
> Add deprecation warning to HTML Imports article

- _redirects.yaml
- main.py
- redirects.py
Check out the YAML file I've added for config information and some examples.
> add redirects yaml code

- content/tutorials/getusermedia/intro/en/index.html
I edited this article based on Google's developer documentation style guide so that it's ready for CDS. I mostly removed first-person references, usage of past and future tense, and gerunds (words that end in -ing, which are hard to localize).
> Edited article for CDS

- content/tutorials/getusermedia/intro/en/index.html
* Edited article for CDS
I edited this article based on Google's developer documentation style guide so that it's for CDS.
I mostly removed first-person references, usage of past and future tense, and gerunds (words that end in -ing, which are hard to localize).
* Addressed Sam's comments
I addressed Sam's comments, including changing URLs from http to https, iFrames to iframes, etc.
* Addressed Francois' comments
Edited for Francois' comments, but I'm not sure how to wrap under 80 characters per line.
* Addressed Francois' remaining edits
* Adjusted for HTML
* Addressed Francois's edits
> Edited article for CDS (#1514)

- content/tutorials/getusermedia/intro/en/index.html
> Made minor residual edits for CDS

- _redirects.yaml
I've just gone through and added ... to the end of each location as that should deal with the double ending slash problem causing things not to redirect afaik.
> dealing with the double slash issue.
